### ISSUE TITLE
Plug-in errors

### ISSUE THREAD

**Issue by edautz** [sweebee/pimatic-nefit#3]
The last days one of my Pimatic instals gives lots of the following error:

After restarting Pimatic it is gone for a while, but then again lots of those errors.

error [pimatic]: An uncaught exception occurred: Error: Uncaught, unspecified "error" event. (XMPP authentication failure)
    at Client.emit (events.js:144:17)
    at Client._handleAuthState (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/lib/Client.js:295:10)
    at Client._handleStanza (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/lib/Client.js:233:12)
    at Client.onStanza (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.onStanza (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:77:13)
    at StreamParser.emit (events.js:169:7)
    at SaxLtx.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/@xmpp/streamparser/index.js:69:14)
    at emitOne (events.js:77:13)
    at SaxLtx.emit (events.js:169:7)
    at SaxLtx._handleTagOpening (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:38:12)
    at SaxLtx.write (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:127:18)
    at StreamParser.write (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/@xmpp/streamparser/index.js:134:17)
    at Connection.onData (/home/pi/pimatic-app/node_modules/pimatic-nefit/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TLSSocket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:537:20)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by sweebee** [comment]
Closing this one since #4 is the same
